### ISSUE TITLE
如何获取指令字符串格式数据

### ISSUE THREAD

**Issue by wzjiscode** [Liu-Jinshuai/printease#8]
现在是通过tspl.getBuffer()获取缓冲区数据，如何直接获取指令拼接的字符串我自己转buffer呢
需求结果：
`
SIZE 100mm,70mm
PRINT 1
`

**Comment by Liu-Jinshuai** [comment]
不好意思，刚看到，您可以使用tspl.getCommand()。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月05日 08:33 |
| 收件人 | Liu-Jinshuai/printease ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [Liu-Jinshuai/printease] 如何获取指令字符串格式数据 (Issue #8) |

现在是通过tspl.getBuffer()获取缓冲区数据，如何直接获取指令拼接的字符串我自己转buffer呢
需求结果：
SIZE 100mm,70mm PRINT 1

**Comment by wzjiscode** [comment]
>

**Comment by wzjiscode** [comment]
> 不好意思，刚看到，您可以使用tspl.getCommand()。
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年12月05日 08:33 | | 收件人 | Liu-Jinshuai/printease ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | [Liu-Jinshuai/printease] 如何获取指令字符串格式数据 (Issue #8) | 现在是通过tspl.getBuffer()获取缓冲区数据，如何直接获取指令拼接的字符串我自己转buffer呢 需求结果： SIZE 100mm,70mm PRINT 1 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

1. tspl.getCommand() 获取到的不是我的预期目标值
[
    83,
    73,
  ...
]
2. 需求结果：
SIZE 100mm,70mm PRINT 1

**Comment by Liu-Jinshuai** [comment]
let charcodes = [72, 101, 108, 108, 111];
let string = String.fromCharCode(...charcodes);
console.log(string);

你可以这么处理

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月06日 10:37 |
| 收件人 | Liu-Jinshuai/printease ***@***.***> |
| 抄送人 | liujinshuai ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [Liu-Jinshuai/printease] 如何获取指令字符串格式数据 (Issue #8) |

不好意思，刚看到，您可以使用tspl.getCommand()。
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年12月05日 08:33 | | 收件人 | Liu-Jinshuai/printease @.> | | 抄送人 | Subscribed @.> | | 主题 | [Liu-Jinshuai/printease] 如何获取指令字符串格式数据 (Issue #8) | 现在是通过tspl.getBuffer()获取缓冲区数据，如何直接获取指令拼接的字符串我自己转buffer呢 需求结果： SIZE 100mm,70mm PRINT 1 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

tspl.getCommand() 获取到的不是我的预期目标值
[
83,
73,
...
]
需求结果：
SIZE 100mm,70mm PRINT 1

**Comment by wzjiscode** [comment]
> let charcodes = [72, 101, 108, 108, 111]; let string = String.fromCharCode(...charcodes); console.log(string); 你可以这么处理
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年12月06日 10:37 | | 收件人 | Liu-Jinshuai/printease ***@***.***> | | 抄送人 | liujinshuai ***@***.***>, Comment ***@***.***> | | 主题 | Re: [Liu-Jinshuai/printease] 如何获取指令字符串格式数据 (Issue #8) | 不好意思，刚看到，您可以使用tspl.getCommand()。 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年12月05日 08:33 | | 收件人 | Liu-Jinshuai/printease @.> | | 抄送人 | Subscribed @.> | | 主题 | [Liu-Jinshuai/printease] 如何获取指令字符串格式数据 (Issue #8) | 现在是通过tspl.getBuffer()获取缓冲区数据，如何直接获取指令拼接的字符串我自己转buffer呢 需求结果： SIZE 100mm,70mm PRINT 1 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> tspl.getCommand() 获取到的不是我的预期目标值 [ 83, 73, ... ] 需求结果： SIZE 100mm,70mm PRINT 1 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

1. 通过大佬的方法成功转为目标结果了 
SIZE 100 mm, 70 mm
GAP 2 mm, 0 mm
DIRECTION 1
CLS
BITMAP 0, 0, 12.5, 70, 0,ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿþÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÇÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿü?ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÃÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿüÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿàÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿþÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿðÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿø?ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÃÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿü?ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿáÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿþÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿà?üÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿþÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÀà?ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿø
BITMAP数据是不是还是异常的，打印机打了个空白纸出来，不用bitmap没问题。


2. 直接通过tspl.getCommand()打印图片是一片黑白
